from stanfordkarel import *

def main():
    pick_beeper()
    turn_left()
    move()
    pick_beeper()
    move()
    pick_beeper()
    move()
    pick_beeper()
    move()
    pick_beeper()
    turn_left()
    move()
    move()
    move()
    move()
    pick_beeper()
    turn_left()
    move()
    pick_beeper()
    move()
    pick_beeper()
    move()
    pick_beeper()
    move()
    pick_beeper()
    turn_right()
    move()
    move()
    move()
    move()
    pick_beeper()
    turn_right()
    move()
    pick_beeper()
    move()
    pick_beeper()
    move()
    pick_beeper()
    move()
    pick_beeper()
    turn_left()
    move()
    move()
    move()
    move()
    pick_beeper()
    turn_left()
    move()
    pick_beeper()
    move()
    pick_beeper()
    move()
    pick_beeper()
    move()
    pick_beeper()
    


def turn_right():
    for i in range(3):
        turn_left()


if __name__ == "__main__":
    run_karel_program()